In [13]:
import ast
import numpy as np
import pandas as pd
import pandas_ta as ta
import tensorflow as tf
import matplotlib.pyplot as plt

from WindowGenerator import WindowGenerator

In [14]:
df = pd.read_csv('BTC_USD_2015-10-08_2020-05-27_Gemini_Hourly.csv')
df.set_index('Date', inplace=True)

df.loc[:, 'ema12'] = df.ta.ema(12)
df.loc[:, 'ema24'] = df.ta.ema(24)
df.loc[:, 'ema48'] = df.ta.ema(48)
df.loc[:, 'vwma'] = df.ta.vwma()
df.loc[:, 'log'] = np.log(df.close)

df.drop(['currency', 'open', 'high', 'low', 'volume'], axis=1, inplace=True)
df = df[48:]
df

,close,ema12,ema24,ema48,vwma,log
Date,,,,,,
2015-10-11 00:00:00,246.30,245.733371,245.733371,245.733371,245.632542,5.506550
2015-10-11 01:00:00,246.30,245.836394,245.836394,245.836394,245.725661,5.506550
2015-10-11 02:00:00,246.30,245.920686,245.920686,245.920686,245.818708,5.506550
2015-10-11 03:00:00,246.30,245.989652,245.989652,245.989652,245.911686,5.506550
2015-10-11 04:00:00,246.30,246.046079,246.046079,246.046079,246.004593,5.506550
...,...,...,...,...,...,...
2020-05-23 19:00:00,9186.01,9179.465780,9179.465780,9179.465780,9169.374777,9.125437
2020-05-23 20:00:00,9238.75,9190.244729,9190.244729,9190.244729,9179.574617,9.131162
2020-05-23 21:00:00,9235.01,9198.383869,9198.383869,9198.383869,9184.846033,9.130757
2020-05-23 22:00:00,9228.26,9203.815893,9203.815893,9203.815893,9195.036730,9.130026
2020-05-23 23:00:00,9175.00,9198.576640,9198.576640,9198.576640,9196.569181,9.124238

In [15]:
# Standardise data
def standardise(df, column, mean, std):
    vals = df[col].values
    df.loc[:, column+'_normal'] = pd.Series((vals - mean) / std, index=df.index, dtype=np.float64)

cols = [x for x in df.columns]

norms = open('norms.txt', 'r').readline().replace('\n', '')
norms = ast.literal_eval(norms)
for col in cols:
    std = norms[col+'_std']
    mean = norms[col+'_mean']
    standardise(df, col, mean, std)

n = len(df)

df.drop([x for x in df.columns.tolist() if 'normal' not in x], axis=1, inplace=True)
train_df = df[0:int(n*0.7)]
val_df = df[int(n*0.7):int(n*0.9)]
test_df = df[int(n*0.9):]

test_df

/home/harvir/Code/venvs/tensorflow_venv/lib/python3.8/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/harvir/Code/venvs/tensorflow_venv/lib/python3.8/site-packages/pandas/core/indexing.py:1048: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item_labels[indexer[info_axis]]] = value
/home/harvir/Code/venvs/tensorflow_venv/lib/python3.8/site-packages/pandas/core/frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,close_normal,ema12_normal,ema24_normal,ema48_normal,vwma_normal,log_normal
Date,,,,,,
2019-12-07 07:00:00,0.972853,0.973179,0.973179,0.973179,0.976296,1.098002
2019-12-07 08:00:00,0.967856,0.972286,0.972286,0.972286,0.975948,1.095918
2019-12-07 09:00:00,0.965558,0.971137,0.971137,0.971137,0.974971,1.094957
2019-12-07 10:00:00,0.968018,0.970644,0.970644,0.970644,0.974592,1.095985
2019-12-07 11:00:00,0.973158,0.971176,0.971176,0.971176,0.974882,1.098129
...,...,...,...,...,...,...
2020-05-23 19:00:00,1.398871,1.397709,1.397709,1.397709,1.394375,1.258460
2020-05-23 20:00:00,1.412471,1.400489,1.400489,1.400489,1.397005,1.263093
2020-05-23 21:00:00,1.411506,1.402588,1.402588,1.402588,1.398364,1.262766
2020-05-23 22:00:00,1.409766,1.403989,1.403989,1.403989,1.400991,1.262174
2020-05-23 23:00:00,1.396032,1.402638,1.402638,1.402638,1.401387,1.257490

In [16]:
INPUT_WIDTH = 20
LABEL_SHIFT = 4
LABEL_WIDTH = 4

window = WindowGenerator(input_width=INPUT_WIDTH, label_width=LABEL_WIDTH, shift=LABEL_SHIFT, 
                         train_df=train_df, val_df=val_df, test_df=test_df,
                         label_columns=['close_normal'])
window

Total window size: 24
Input indices: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Label indices: [20 21 22 23]
Label column name(s): ['close_normal']

In [17]:
model = tf.keras.models.load_model('BTC_USD_122448EMAs_VWAP_LOG/model')

In [18]:
model.evaluate(window.test)

42/42 [==============================] - 2s 36ms/step - loss: 1.8700

1.8699779510498047

In [ ]:
i = 0

for i in range(5, 20):
    new_df = test_df.iloc[(INPUT_WIDTH*i):(INPUT_WIDTH*(i+1))+LABEL_SHIFT]
    input = tf.stack([row.values for _, row in new_df.iloc[:INPUT_WIDTH].iterrows()])
    input = tf.expand_dims(input, axis=0)

#     actual = np.exp(model.predict(input)[0][0])
#     expected = np.exp(new_df.iloc[-1]['close_normal'])
#     new_df.loc[:, 'close'] = pd.Series(np.exp(new_df['close_normal'].values), index=new_df.index)

    actual = (model.predict(input)[0][0] * norms['close_std']) + norms['close_mean']
    expected = (new_df.iloc[-1]['close_normal'] * norms['close_std']) + norms['close_mean']
    new_df.loc[:, 'close'] = pd.Series((new_df['close_normal'].values*norms['close_std'])+norms['close_mean'], index=new_df.index)

    if LABEL_SHIFT > 1:
        plt.plot([x for x in range(-INPUT_WIDTH, 1)], new_df['close'][:INPUT_WIDTH+1])
        plt.plot([x for x in range(0, LABEL_SHIFT)], new_df['close'][INPUT_WIDTH:], linestyle='dotted')
        plt.plot([0, LABEL_SHIFT-1], 
                     [new_df['close'][INPUT_WIDTH], actual],
                     marker='o', linestyle='dotted')
    else:
        plt.plot(new_df.index, new_df['close'])
        plt.plot(new_df.index[-1], actual, marker='o')
    print(f'Diff is {actual-expected}')
    plt.show()

In [ ]:
BIAS = 0

fig, axes = plt.subplots(nrows=5, ncols=2, figsize=(40, 60))

for i in range(3, 13):
    new_df = test_df.iloc[(INPUT_WIDTH*i):(INPUT_WIDTH*(i+1))+LABEL_SHIFT]
    input = tf.stack([row.values for _, row in new_df.iterrows()])[:-1]
    input = tf.expand_dims(input, axis=0)
    
    actual = ((model.predict(input)*STD)+MEAN)[0][0]
    expected = (tf.stack([row.values for _, row in new_df.iterrows()])[-1].numpy()[0]*STD)+MEAN
    
    new_df.loc[:, 'close'] = pd.Series((new_df['close_normal'].values*STD)+MEAN, index=new_df.index)
    
    
    if i%2 == 0:
        j = 1
    else:
        j = 0
    
    i = i-3
    map = {0: 0, 1: 0, 2:1, 3:1, 4:2, 5:2, 6:3, 7:3, 8:4, 9:4}
    i = map[i]
    if LABEL_SHIFT > 1:
        # axes[i].plot(new_df.index[:INPUT_WIDTH+1], new_df['close'][:INPUT_WIDTH+1])
        axes[i][j].plot([x for x in range(-INPUT_WIDTH, 1)], new_df['close'][:INPUT_WIDTH+1])
        # axes[i].plot(new_df.index[INPUT_WIDTH:], new_df['close'][INPUT_WIDTH:], linestyle='dotted')
        axes[i][j].plot([x for x in range(0, LABEL_SHIFT)], new_df['close'][INPUT_WIDTH:], linestyle='dotted')
#         axes[i].plot([new_df.index[INPUT_WIDTH], new_df.index[-1]], 
#                      [new_df['close'][INPUT_WIDTH], actual],
#                      marker='o', linestyle='dotted')
        axes[i][j].plot([0, LABEL_SHIFT-1], 
                     [new_df['close'][INPUT_WIDTH], actual],
                     marker='o', linestyle='dotted')
        axes[i][j].set_title(f'{new_df.index[0]} to {new_df.index[-1]}')
        axes[i][j].set_xlabel('Tn (hour)')
        axes[i][j].set_ylabel('Price (USD)')
    else:
        axes[i].plot(new_df.index, new_df['close'])
        axes[i].plot(new_df.index[-1], actual, marker='o')
    print(f'Diff is {actual-expected}')

plt.show()

In [ ]:
model.save('BTC_USD_122448EMAs_VWAP_LOG', save_format='tf')